// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Footer  documents
 */
interface FooterDocumentData {
  /**
   * Footer Title field in *Footer *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_title: prismic.RichTextField;

  /**
   * Footer Sub Title field in *Footer *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_sub_title: prismic.RichTextField;

  /**
   * Button Label field in *Footer *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_label: prismic.RichTextField;

  /**
   * Button Link field in *Footer *
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Footer logo field in *Footer *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Footer description field in *Footer *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_description: prismic.RichTextField;

  /**
   * Slice Zone field in *Footer *
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer  document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type GlobalMenuDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Global Menu documents
 */
interface GlobalMenuDocumentData {
  /**
   * Company Name field in *Global Menu*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_menu.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name: prismic.RichTextField;

  /**
   * Company Logo field in *Global Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_menu.company_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Header Menu Label field in *Global Menu*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_menu.header_menu_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header_menu_label: prismic.RichTextField;

  /**
   * Header Menu Link field in *Global Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_menu.header_menu_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  header_menu_link: prismic.LinkField;

  /**
   * Slice Zone field in *Global Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: global_menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GlobalMenuDocumentDataSlicesSlice>;
}

/**
 * Global Menu document from Prismic
 *
 * - **API ID**: `global_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalMenuDocumentData>,
    "global_menu",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | StoryBlockSlice
  | FaqSectionSlice
  | BlockonImageSlice
  | FormSectionSlice
  | SolutionsBlockSlice
  | FooterInfoSlice
  | TimeLineBlockSlice
  | AboutBlockSlice
  | CtaBlockSlice
  | ServicesBlockSlice
  | HeroSectionSlice
  | FeaturesBlockSlice
  | LogosBlockSlice
  | FeatureSectionSlice
  | IntegrationsBlockSlice
  | BlogSectionSlice
  | CaseStudiesBlockSlice
  | NavigationItemSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | GlobalMenuDocument
  | PageDocument;

/**
 * Primary content in *AboutBlock → Primary*
 */
export interface AboutBlockSliceDefaultPrimary {
  /**
   * Title field in *AboutBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutBlock → Items*
 */
export interface AboutBlockSliceDefaultItem {
  /**
   * Count Item Label field in *AboutBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.items[].count_item_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  count_item_label: prismic.RichTextField;

  /**
   * Count field in *AboutBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_block.items[].count
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  count: prismic.KeyTextField;
}

/**
 * Default variation for AboutBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutBlockSliceDefaultPrimary>,
  Simplify<AboutBlockSliceDefaultItem>
>;

/**
 * Slice variation for *AboutBlock*
 */
type AboutBlockSliceVariation = AboutBlockSliceDefault;

/**
 * AboutBlock Shared Slice
 *
 * - **API ID**: `about_block`
 * - **Description**: AboutBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutBlockSlice = prismic.SharedSlice<
  "about_block",
  AboutBlockSliceVariation
>;

/**
 * Primary content in *KeepInTouchBlock → Primary*
 */
export interface BlockonImageSliceDefaultPrimary {
  /**
   * Title field in *KeepInTouchBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *KeepInTouchBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *KeepInTouchBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *KeepInTouchBlock → Items*
 */
export interface BlockonImageSliceDefaultItem {
  /**
   * CategoryName field in *KeepInTouchBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.items[].categoryname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  categoryname: prismic.RichTextField;

  /**
   * BlockTitle field in *KeepInTouchBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.items[].blocktitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blocktitle: prismic.RichTextField;

  /**
   * BlockDescription field in *KeepInTouchBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.items[].blockdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blockdescription: prismic.RichTextField;

  /**
   * SocialMediaIcons field in *KeepInTouchBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blockon_image.items[].socialmediaicons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialmediaicons: prismic.LinkField;
}

/**
 * Default variation for KeepInTouchBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockonImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlockonImageSliceDefaultPrimary>,
  Simplify<BlockonImageSliceDefaultItem>
>;

/**
 * Slice variation for *KeepInTouchBlock*
 */
type BlockonImageSliceVariation = BlockonImageSliceDefault;

/**
 * KeepInTouchBlock Shared Slice
 *
 * - **API ID**: `blockon_image`
 * - **Description**: BlockonImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockonImageSlice = prismic.SharedSlice<
  "blockon_image",
  BlockonImageSliceVariation
>;

/**
 * Primary content in *BlogSection → Primary*
 */
export interface BlogSectionSliceDefaultPrimary {
  /**
   * Title field in *BlogSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *BlogSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Blogs Link field in *BlogSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.primary.blogs_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blogs_link: prismic.LinkField;
}

/**
 * Primary content in *BlogSection → Items*
 */
export interface BlogSectionSliceDefaultItem {
  /**
   * Title field in *BlogSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Category field in *BlogSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Description field in *BlogSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *BlogSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link to detail page field in *BlogSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].link_to_detail_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_detail_page: prismic.LinkField;
}

/**
 * Default variation for BlogSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSectionSliceDefaultPrimary>,
  Simplify<BlogSectionSliceDefaultItem>
>;

/**
 * Primary content in *BlogSection → Items*
 */
export interface BlogSectionSliceBlogItemsItem {
  /**
   * Title field in *BlogSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Category field in *BlogSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Description field in *BlogSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *BlogSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link to detail page field in *BlogSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].link_to_detail_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_detail_page: prismic.LinkField;
}

/**
 * BlogItems variation for BlogSection Slice
 *
 * - **API ID**: `blogItems`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSliceBlogItems = prismic.SharedSliceVariation<
  "blogItems",
  Record<string, never>,
  Simplify<BlogSectionSliceBlogItemsItem>
>;

/**
 * Slice variation for *BlogSection*
 */
type BlogSectionSliceVariation =
  | BlogSectionSliceDefault
  | BlogSectionSliceBlogItems;

/**
 * BlogSection Shared Slice
 *
 * - **API ID**: `blog_section`
 * - **Description**: BlogSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSlice = prismic.SharedSlice<
  "blog_section",
  BlogSectionSliceVariation
>;

/**
 * Primary content in *CaseStudiesBlock → Primary*
 */
export interface CaseStudiesBlockSliceDefaultPrimary {
  /**
   * Title field in *CaseStudiesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *CaseStudiesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * View All Link field in *CaseStudiesBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.primary.view_all_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  view_all_link: prismic.LinkField;
}

/**
 * Primary content in *CaseStudiesBlock → Items*
 */
export interface CaseStudiesBlockSliceDefaultItem {
  /**
   * Category field in *CaseStudiesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Title field in *CaseStudiesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CaseStudiesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *CaseStudiesBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link to case field in *CaseStudiesBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies_block.items[].link_to_case
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_case: prismic.LinkField;
}

/**
 * Default variation for CaseStudiesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudiesBlockSliceDefaultPrimary>,
  Simplify<CaseStudiesBlockSliceDefaultItem>
>;

/**
 * Slice variation for *CaseStudiesBlock*
 */
type CaseStudiesBlockSliceVariation = CaseStudiesBlockSliceDefault;

/**
 * CaseStudiesBlock Shared Slice
 *
 * - **API ID**: `case_studies_block`
 * - **Description**: CaseStudiesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesBlockSlice = prismic.SharedSlice<
  "case_studies_block",
  CaseStudiesBlockSliceVariation
>;

/**
 * Primary content in *CtaBlock → Primary*
 */
export interface CtaBlockSliceDefaultPrimary {
  /**
   * Title field in *CtaBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *CtaBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Image field in *CtaBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CtaBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaBlock*
 */
type CtaBlockSliceVariation = CtaBlockSliceDefault;

/**
 * CtaBlock Shared Slice
 *
 * - **API ID**: `cta_block`
 * - **Description**: CtaBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSlice = prismic.SharedSlice<
  "cta_block",
  CtaBlockSliceVariation
>;

/**
 * Primary content in *FaqSection → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Title field in *FaqSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *FaqSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *FaqSection → Items*
 */
export interface FaqSectionSliceDefaultItem {
  /**
   * Question field in *FaqSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *FaqSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  Simplify<FaqSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *OverviewSection → Primary*
 */
export interface FeatureSectionSliceDefaultPrimary {
  /**
   * Title field in *OverviewSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *OverviewSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Feature Image field in *OverviewSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_section.primary.feature_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;
}

/**
 * Default variation for OverviewSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OverviewSection*
 */
type FeatureSectionSliceVariation = FeatureSectionSliceDefault;

/**
 * OverviewSection Shared Slice
 *
 * - **API ID**: `feature_section`
 * - **Description**: FeatureSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureSectionSlice = prismic.SharedSlice<
  "feature_section",
  FeatureSectionSliceVariation
>;

/**
 * Primary content in *FeaturesBlock → Primary*
 */
export interface FeaturesBlockSliceDefaultPrimary {
  /**
   * Title field in *FeaturesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *FeaturesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Block background field in *FeaturesBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: WhiteTheme
   * - **API ID Path**: features_block.primary.block_background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  block_background: prismic.SelectField<"WhiteTheme" | "GrayTheme", "filled">;
}

/**
 * Primary content in *FeaturesBlock → Items*
 */
export interface FeaturesBlockSliceDefaultItem {
  /**
   * Title field in *FeaturesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *FeaturesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.items[].sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Image field in *FeaturesBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *FeaturesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for FeaturesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesBlockSliceDefaultPrimary>,
  Simplify<FeaturesBlockSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturesBlock*
 */
type FeaturesBlockSliceVariation = FeaturesBlockSliceDefault;

/**
 * FeaturesBlock Shared Slice
 *
 * - **API ID**: `features_block`
 * - **Description**: FeaturesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesBlockSlice = prismic.SharedSlice<
  "features_block",
  FeaturesBlockSliceVariation
>;

/**
 * Primary content in *FooterInfo → Primary*
 */
export interface FooterInfoSliceDefaultPrimary {
  /**
   * Footer Title field in *FooterInfo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_info.primary.footer_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_title: prismic.RichTextField;

  /**
   * Footer Sub Title field in *FooterInfo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_info.primary.footer_sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_sub_title: prismic.RichTextField;

  /**
   * Button Label field in *FooterInfo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_info.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_label: prismic.RichTextField;

  /**
   * Button Link field in *FooterInfo → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_info.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for FooterInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterInfo*
 */
type FooterInfoSliceVariation = FooterInfoSliceDefault;

/**
 * FooterInfo Shared Slice
 *
 * - **API ID**: `footer_info`
 * - **Description**: FooterInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterInfoSlice = prismic.SharedSlice<
  "footer_info",
  FooterInfoSliceVariation
>;

/**
 * Primary content in *FormSection → Primary*
 */
export interface FormSectionSliceDefaultPrimary {
  /**
   * Title field in *FormSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *FormSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * ButtonLabel field in *FormSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.primary.buttonlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttonlabel: prismic.RichTextField;
}

/**
 * Default variation for FormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormSection*
 */
type FormSectionSliceVariation = FormSectionSliceDefault;

/**
 * FormSection Shared Slice
 *
 * - **API ID**: `form_section`
 * - **Description**: FormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSectionSlice = prismic.SharedSlice<
  "form_section",
  FormSectionSliceVariation
>;

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub title field in *HeroSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Menu Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.menu
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  menu: prismic.RichTextField;

  /**
   * Menu Link field in *HeroSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Hero Image field in *HeroSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroSectionSliceHeroNoButtonSmallBannerPrimary {
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub title field in *HeroSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Menu Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.menu
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  menu: prismic.RichTextField;

  /**
   * Menu Link field in *HeroSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Hero Image field in *HeroSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * HeroNoButtonSmallBanner variation for HeroSection Slice
 *
 * - **API ID**: `heroNoButtonSmallBanner`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceHeroNoButtonSmallBanner =
  prismic.SharedSliceVariation<
    "heroNoButtonSmallBanner",
    Simplify<HeroSectionSliceHeroNoButtonSmallBannerPrimary>,
    never
  >;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceHeroNoButtonSmallBanner;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *IntegrationsBlock → Primary*
 */
export interface IntegrationsBlockSliceDefaultPrimary {
  /**
   * Title field in *IntegrationsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *IntegrationsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;
}

/**
 * Primary content in *IntegrationsBlock → Items*
 */
export interface IntegrationsBlockSliceDefaultItem {
  /**
   * Category field in *IntegrationsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations_block.items[].category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Title field in *IntegrationsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Image field in *IntegrationsBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *IntegrationsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: integrations_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for IntegrationsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntegrationsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntegrationsBlockSliceDefaultPrimary>,
  Simplify<IntegrationsBlockSliceDefaultItem>
>;

/**
 * Slice variation for *IntegrationsBlock*
 */
type IntegrationsBlockSliceVariation = IntegrationsBlockSliceDefault;

/**
 * IntegrationsBlock Shared Slice
 *
 * - **API ID**: `integrations_block`
 * - **Description**: IntegrationsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntegrationsBlockSlice = prismic.SharedSlice<
  "integrations_block",
  IntegrationsBlockSliceVariation
>;

/**
 * Primary content in *LogosBlock → Primary*
 */
export interface LogosBlockSliceDefaultPrimary {
  /**
   * Title field in *LogosBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *LogosBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Block background field in *LogosBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the background color of the block
   * - **Default Value**: WhiteTheme
   * - **API ID Path**: logos_block.primary.block_background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  block_background: prismic.SelectField<"WhiteTheme" | "GrayTheme", "filled">;
}

/**
 * Primary content in *LogosBlock → Items*
 */
export interface LogosBlockSliceDefaultItem {
  /**
   * Client Logo field in *LogosBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos_block.items[].client_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  client_logo: prismic.ImageField<never>;
}

/**
 * Default variation for LogosBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogosBlockSliceDefaultPrimary>,
  Simplify<LogosBlockSliceDefaultItem>
>;

/**
 * Slice variation for *LogosBlock*
 */
type LogosBlockSliceVariation = LogosBlockSliceDefault;

/**
 * LogosBlock Shared Slice
 *
 * - **API ID**: `logos_block`
 * - **Description**: LogosBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosBlockSlice = prismic.SharedSlice<
  "logos_block",
  LogosBlockSliceVariation
>;

/**
 * Primary content in *NavigationItem → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationItemSliceDefaultItem {
  /**
   * Child Name field in *NavigationItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  child_name: prismic.RichTextField;

  /**
   * Child Link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  child_link: prismic.LinkField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  Simplify<NavigationItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *ServicesBlock → Primary*
 */
export interface ServicesBlockSliceDefaultPrimary {
  /**
   * Title field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Image field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ServicesBlock → Items*
 */
export interface ServicesBlockSliceDefaultItem {
  /**
   * Service Category field in *ServicesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].service_category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_category: prismic.RichTextField;

  /**
   * Service Name field in *ServicesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].service_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_name: prismic.RichTextField;

  /**
   * Description field in *ServicesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link to service field in *ServicesBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].link_to_service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_service: prismic.LinkField;
}

/**
 * Default variation for ServicesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesBlockSliceDefaultPrimary>,
  Simplify<ServicesBlockSliceDefaultItem>
>;

/**
 * Primary content in *ServicesBlock → Primary*
 */
export interface ServicesBlockSliceBlockWithoutOverlapCardPrimary {
  /**
   * Title field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Image field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ServicesBlock → Items*
 */
export interface ServicesBlockSliceBlockWithoutOverlapCardItem {
  /**
   * Service Category field in *ServicesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].service_category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_category: prismic.RichTextField;

  /**
   * Service Name field in *ServicesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].service_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_name: prismic.RichTextField;

  /**
   * Description field in *ServicesBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link to service field in *ServicesBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].link_to_service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_service: prismic.LinkField;
}

/**
 * Block Without Overlap Card variation for ServicesBlock Slice
 *
 * - **API ID**: `blockWithoutOverlapCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSliceBlockWithoutOverlapCard =
  prismic.SharedSliceVariation<
    "blockWithoutOverlapCard",
    Simplify<ServicesBlockSliceBlockWithoutOverlapCardPrimary>,
    Simplify<ServicesBlockSliceBlockWithoutOverlapCardItem>
  >;

/**
 * Slice variation for *ServicesBlock*
 */
type ServicesBlockSliceVariation =
  | ServicesBlockSliceDefault
  | ServicesBlockSliceBlockWithoutOverlapCard;

/**
 * ServicesBlock Shared Slice
 *
 * - **API ID**: `services_block`
 * - **Description**: ServicesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSlice = prismic.SharedSlice<
  "services_block",
  ServicesBlockSliceVariation
>;

/**
 * Primary content in *SolutionsBlock → Primary*
 */
export interface SolutionsBlockSliceDefaultPrimary {
  /**
   * Title field in *SolutionsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sub Title field in *SolutionsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Primary solution field in *SolutionsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.primary.primary_solution
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  primary_solution: prismic.RichTextField;

  /**
   * Primary solution description field in *SolutionsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.primary.primary_solution_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  primary_solution_description: prismic.RichTextField;

  /**
   * Primary Solution  Link field in *SolutionsBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.primary.primary_solution_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_solution_link: prismic.LinkField;

  /**
   * Image field in *SolutionsBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *SolutionsBlock → Items*
 */
export interface SolutionsBlockSliceDefaultItem {
  /**
   * Solution field in *SolutionsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.items[].solution
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  solution: prismic.RichTextField;

  /**
   * Description field in *SolutionsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *SolutionsBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *SolutionsBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SolutionsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionsBlockSliceDefaultPrimary>,
  Simplify<SolutionsBlockSliceDefaultItem>
>;

/**
 * Slice variation for *SolutionsBlock*
 */
type SolutionsBlockSliceVariation = SolutionsBlockSliceDefault;

/**
 * SolutionsBlock Shared Slice
 *
 * - **API ID**: `solutions_block`
 * - **Description**: SolutionsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionsBlockSlice = prismic.SharedSlice<
  "solutions_block",
  SolutionsBlockSliceVariation
>;

/**
 * Primary content in *StickyBar → Primary*
 */
export interface StickyBarSliceDefaultPrimary {
  /**
   * UID field in *StickyBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_bar.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  uid: prismic.RichTextField;
}

/**
 * Primary content in *StickyBar → Items*
 */
export interface StickyBarSliceDefaultItem {
  /**
   * Menu Label field in *StickyBar → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_bar.items[].menu_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  menu_label: prismic.RichTextField;

  /**
   * Scroll to Block Id field in *StickyBar → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the ID of the block to navigate to that block.
   * - **API ID Path**: sticky_bar.items[].scroll_to_block_id
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_to_block_id: prismic.SelectField<
    "aboutOveriewSection" | "overiewSection"
  >;
}

/**
 * Default variation for StickyBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickyBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StickyBarSliceDefaultPrimary>,
  Simplify<StickyBarSliceDefaultItem>
>;

/**
 * Slice variation for *StickyBar*
 */
type StickyBarSliceVariation = StickyBarSliceDefault;

/**
 * StickyBar Shared Slice
 *
 * - **API ID**: `sticky_bar`
 * - **Description**: StickyBar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickyBarSlice = prismic.SharedSlice<
  "sticky_bar",
  StickyBarSliceVariation
>;

/**
 * Primary content in *StoryBlock → Primary*
 */
export interface StoryBlockSliceDefaultPrimary {
  /**
   * Title field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *StoryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Heading field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Author field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.author
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * PublishLabel field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.publishlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  publishlabel: prismic.RichTextField;

  /**
   * AuthorImage field in *StoryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.authorimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  authorimage: prismic.ImageField<never>;

  /**
   * AuthorName field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.authorname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  authorname: prismic.RichTextField;

  /**
   * PublishDate field in *StoryBlock → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.publishdate
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishdate: prismic.DateField;
}

/**
 * Default variation for StoryBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoryBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoryBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *StoryBlock → Primary*
 */
export interface StoryBlockSliceWithoutAuthorPrimary {
  /**
   * Title field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *StoryBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Heading field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *StoryBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_block.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;
}

/**
 * WithoutAuthor variation for StoryBlock Slice
 *
 * - **API ID**: `withoutAuthor`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoryBlockSliceWithoutAuthor = prismic.SharedSliceVariation<
  "withoutAuthor",
  Simplify<StoryBlockSliceWithoutAuthorPrimary>,
  never
>;

/**
 * Slice variation for *StoryBlock*
 */
type StoryBlockSliceVariation =
  | StoryBlockSliceDefault
  | StoryBlockSliceWithoutAuthor;

/**
 * StoryBlock Shared Slice
 *
 * - **API ID**: `story_block`
 * - **Description**: StoryBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoryBlockSlice = prismic.SharedSlice<
  "story_block",
  StoryBlockSliceVariation
>;

/**
 * Primary content in *TimeLineBlock → Primary*
 */
export interface TimeLineBlockSliceDefaultPrimary {
  /**
   * Title field in *TimeLineBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *TimeLineBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TimeLineBlock → Items*
 */
export interface TimeLineBlockSliceDefaultItem {
  /**
   * Description field in *TimeLineBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Year field in *TimeLineBlock → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line_block.items[].year
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField;
}

/**
 * Default variation for TimeLineBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimeLineBlockSliceDefaultPrimary>,
  Simplify<TimeLineBlockSliceDefaultItem>
>;

/**
 * Slice variation for *TimeLineBlock*
 */
type TimeLineBlockSliceVariation = TimeLineBlockSliceDefault;

/**
 * TimeLineBlock Shared Slice
 *
 * - **API ID**: `time_line_block`
 * - **Description**: TimeLineBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineBlockSlice = prismic.SharedSlice<
  "time_line_block",
  TimeLineBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      GlobalMenuDocument,
      GlobalMenuDocumentData,
      GlobalMenuDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutBlockSlice,
      AboutBlockSliceDefaultPrimary,
      AboutBlockSliceDefaultItem,
      AboutBlockSliceVariation,
      AboutBlockSliceDefault,
      BlockonImageSlice,
      BlockonImageSliceDefaultPrimary,
      BlockonImageSliceDefaultItem,
      BlockonImageSliceVariation,
      BlockonImageSliceDefault,
      BlogSectionSlice,
      BlogSectionSliceDefaultPrimary,
      BlogSectionSliceDefaultItem,
      BlogSectionSliceBlogItemsItem,
      BlogSectionSliceVariation,
      BlogSectionSliceDefault,
      BlogSectionSliceBlogItems,
      CaseStudiesBlockSlice,
      CaseStudiesBlockSliceDefaultPrimary,
      CaseStudiesBlockSliceDefaultItem,
      CaseStudiesBlockSliceVariation,
      CaseStudiesBlockSliceDefault,
      CtaBlockSlice,
      CtaBlockSliceDefaultPrimary,
      CtaBlockSliceVariation,
      CtaBlockSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceDefaultItem,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FeatureSectionSlice,
      FeatureSectionSliceDefaultPrimary,
      FeatureSectionSliceVariation,
      FeatureSectionSliceDefault,
      FeaturesBlockSlice,
      FeaturesBlockSliceDefaultPrimary,
      FeaturesBlockSliceDefaultItem,
      FeaturesBlockSliceVariation,
      FeaturesBlockSliceDefault,
      FooterInfoSlice,
      FooterInfoSliceDefaultPrimary,
      FooterInfoSliceVariation,
      FooterInfoSliceDefault,
      FormSectionSlice,
      FormSectionSliceDefaultPrimary,
      FormSectionSliceVariation,
      FormSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceHeroNoButtonSmallBannerPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceHeroNoButtonSmallBanner,
      IntegrationsBlockSlice,
      IntegrationsBlockSliceDefaultPrimary,
      IntegrationsBlockSliceDefaultItem,
      IntegrationsBlockSliceVariation,
      IntegrationsBlockSliceDefault,
      LogosBlockSlice,
      LogosBlockSliceDefaultPrimary,
      LogosBlockSliceDefaultItem,
      LogosBlockSliceVariation,
      LogosBlockSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefaultItem,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ServicesBlockSlice,
      ServicesBlockSliceDefaultPrimary,
      ServicesBlockSliceDefaultItem,
      ServicesBlockSliceBlockWithoutOverlapCardPrimary,
      ServicesBlockSliceBlockWithoutOverlapCardItem,
      ServicesBlockSliceVariation,
      ServicesBlockSliceDefault,
      ServicesBlockSliceBlockWithoutOverlapCard,
      SolutionsBlockSlice,
      SolutionsBlockSliceDefaultPrimary,
      SolutionsBlockSliceDefaultItem,
      SolutionsBlockSliceVariation,
      SolutionsBlockSliceDefault,
      StickyBarSlice,
      StickyBarSliceDefaultPrimary,
      StickyBarSliceDefaultItem,
      StickyBarSliceVariation,
      StickyBarSliceDefault,
      StoryBlockSlice,
      StoryBlockSliceDefaultPrimary,
      StoryBlockSliceWithoutAuthorPrimary,
      StoryBlockSliceVariation,
      StoryBlockSliceDefault,
      StoryBlockSliceWithoutAuthor,
      TimeLineBlockSlice,
      TimeLineBlockSliceDefaultPrimary,
      TimeLineBlockSliceDefaultItem,
      TimeLineBlockSliceVariation,
      TimeLineBlockSliceDefault,
    };
  }
}
