// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_block: dynamic(() => import("./AboutBlock")),
  blockon_image: dynamic(() => import("./KeepInTouchBlock")),
  blog_section: dynamic(() => import("./BlogSection")),
  case_studies_block: dynamic(() => import("./CaseStudiesBlock")),
  cta_block: dynamic(() => import("./CtaBlock")),
  faq_section: dynamic(() => import("./FaqSection")),
  feature_section: dynamic(() => import("./OverviewSection")),
  features_block: dynamic(() => import("./FeaturesBlock")),
  footer_info: dynamic(() => import("./FooterInfo")),
  form_section: dynamic(() => import("./FormSection")),
  hero_section: dynamic(() => import("./HeroSection")),
  integrations_block: dynamic(() => import("./IntegrationsBlock")),
  logos_block: dynamic(() => import("./LogosBlock")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  rich_text: dynamic(() => import("./RichText")),
  services_block: dynamic(() => import("./ServicesBlock")),
  solutions_block: dynamic(() => import("./SolutionsBlock")),
  sticky_bar: dynamic(() => import("./StickyBar")),
  story_block: dynamic(() => import("./StoryBlock")),
  time_line_block: dynamic(() => import("./TimeLineBlock")),
};
